---
# tasks file for devops-jan-web
     - name: "Install package"
       yum:
         name: nginx
         state: latest

     - name: "Copy web content"
       copy:
         src: index.html
         dest: /var/www/html

     - name: "Copy config"
       template:
         src: nginx-config.j2
         dest: /etc/nginx/sites-enabled/default
       notify:
         - Restart service


